server:
  port: 9898

spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
  web:
    resources:
      static-locations: file:/root/todo-list

markerhub:
  jwt:
    secret: f4e2e52034348f86b67cde581c0f9eb5
    expire: 604800
    header:

logging:
  level:
    zhi.yuan.todolist.mapper: debug
