# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.2.100:3306/todo-list?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: Future@123
shiro-redis:
  enabled: true
  redis-manager:
    host: 192.168.2.100:6379